version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: your-access-key
      MINIO_ROOT_PASSWORD: your-secret-key
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"   # API порт
      - "9001:9001"   # WebUI порт
    command: server /data
    restart: always

  media_service:
    build: .
    environment:
      MINIO_SERVER_URL: "http://minio:9000"
      MINIO_ROOT_USER: your-access-key
      MINIO_ROOT_PASSWORD: your-secret-key
    depends_on:
      - minio
    ports:
      - "8000:8000"
